### ISSUE TITLE
There is a console errors then the user enter to the field some value

### ISSUE THREAD

**Issue by amirovar** [aubrianpeters/pbivisuals#3]
1.	Go to web powerBI
2.	Import visual
3.	Import DataSet
4.	Add visual to the report
5.	Set some value for the any field
Actual result: there are console errors
Expected result: no errors

log:
onDataChanged(customVisual:PBI_CV_89A3936B_554F_4E39_9732_FE9E1ED899DF): 0.964ms
Visual exception TypeError: Cannot read property 'metadata' of undefined
    at e (PBI_CV_89A3936B_554F_4E39_9732_FE9E1ED899DF.js:1:1816)
    at t.update (PBI_CV_89A3936B_554F_4E39_9732_FE9E1ED899DF.js:1:2854)
    at VisualAdapter.update (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:45746:40)
    at https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:45335:45
    at VisualSafeExecutionWrapper.executeSafely (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:45387:28)
    at VisualSafeExecutionWrapper.update (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:45334:26)
    at VisualController.visualUpdate (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:47320:43)
    at VisualController.onViewportChanged (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:47140:26)
    at https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:47114:35
    at Scope.$digest (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.dependencies.bundle.js:32882:23)
AI: USRACT_StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters." props:"{value:TypeError: Cannot read property 'metadata' of undefined\n    at e (PBI_CV_89A3936B_554F_4E39_9732_FE9E1ED899DF.js:1:1816)\n    at t.update (PBI_CV_89A3936B_554F_4E39_9732_FE9E1ED899DF.js:1:2854)\n    at VisualAdapter.update (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:45746:40)\n    at https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:45335:45\n    at VisualSafeExecutionWrapper.executeSafely (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:45387:28)\n    at VisualSafeExecutionWrapper.update (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:45334:26)\n    at VisualController.visualUpdate (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:47320:43)\n    at VisualController.onViewportChanged (https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:47140:26)\n    at https://app.powerbi.com/13.0.1605.489/scripts/powerbiportal.common.bundle.js:47114:35\n    at Sc}"
update(customVisual:PBI_CV_89A3936B_554F_4E39_9732_FE9E1ED899DF): 7.293ms
update(customVisual:PBI_CV_89A3936B_554F_4E39_9732_FE9E1ED899DF): 1.956ms

**Comment by aubrianpeters** [comment]
Couldn't replicate but can see how it's possible and added this commit to prevent.https://github.com/aubrianpeters/pbivisuals/commit/3d54991ddb56d5727cbdc4f011c16788803de70c
